name: AI Code Review with Full Context
on: [pull_request]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # This will fetch the entire repository history

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install anthropic

      - name: AI Code Review
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          python <<EOF
          import os
          import glob
          from anthropic import Anthropic

          anthropic = Anthropic(api_key=os.environ['ANTHROPIC_API_KEY'])

          def get_repo_summary():
              summary = "Repository structure:\n"
              for root, dirs, files in os.walk('.'):
                  if '.git' in dirs:
                      dirs.remove('.git')
                  path = root.split(os.sep)
                  summary += (len(path) - 1) * '  ' + os.path.basename(root) + '/\n'
                  for file in files:
                      summary += len(path) * '  ' + file + '\n'
              return summary

          repo_summary = get_repo_summary()

          changed_files = "${{ steps.changed-files.outputs.all_changed_files }}".split()

          for file in changed_files:
              if file.endswith(('.py', '.js', '.java', '.ts', '.css', '.html')):
                  with open(file, 'r') as f:
                      content = f.read()

                  prompt = f"""You are an AI code reviewer. You have access to the full repository structure.
                  Repository summary:
                  {repo_summary}

                  Now, review the following file: {file}

                  Here's the content:
                  {content}

                  Please provide a thorough code review, considering:
                  1. Code quality and best practices
                  2. Potential bugs or issues
                  3. Performance considerations
                  4. How well it fits with the overall project structure
                  5. Suggestions for improvement

                  Format your review as markdown bullet points."""

                  response = anthropic.messages.create(
                      model="claude-3-sonnet-20240229",
                      max_tokens=2000,
                      messages=[{"role": "user", "content": prompt}]
                  )

                  review = response.content[0].text

                  os.system(f'gh pr comment ${{ github.event.pull_request.number }} --body "AI Review for {file}:\n{review}"')

          EOF